version: 2.1
workflows:
  test_app:
    jobs:
      - test_only:
          filters:
            branches:
              ignore: master
      - test_and_upload:
          filters:
            branches:
              only: master
jobs:
  test_only:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install
          command: npm ci
      - run:
          name: Test
          command: npm t
  test_and_upload:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install
          command: npm ci
      - run:
          name: Test
          command: npm t && npm run badge
      - run:
          name: Coverage
          command: npx tubs upload ./coverage
      - run:
          name: Badge Purge
          command: npx camo-purge --repository https://github.com/jchancehud/especial
